{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJUWE1qdHhGbUdPS04wLUdtbDloZWciLCJpYXQiOjE1ODg0MTE4MDIsImV4cCI6MTU4ODQxMzAwMn0.L4KtRK3BAszsgQG9UIvXkNshjoo0XfCw8p4vQmh5_Gc",
  "expireDate": "2020-05-02T09:50:02.548Z",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJUWE1qdHhGbUdPS04wLUdtbDloZWciLCJpYXQiOjE1ODg0MTE2NzF9.VkS0wlk9yf1FVkx6i_CzrhlgykLpILZBG0XuX2rxiYQ"
}

# AUTH
### me
GET http://localhost:3001/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJUWE1qdHhGbUdPS04wLUdtbDloZWciLCJpYXQiOjE1ODg0MTE2NzEsImV4cCI6MTU4ODQxMjg3MX0.h2BEMjDikk_cwql-4cCgvc_xw8C0Tw5HFZl--0CRGfs

### sign up
POST http://localhost:3001/signup
Content-Type: application/json

{
  "login": "admin",
  "password": "123"
}

### sign in
POST http://localhost:3001/signin
Content-Type: application/json

{
  "login": "admin",
  "password": "123"
}

### refresh token
POST http://localhost:3001/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJUWE1qdHhGbUdPS04wLUdtbDloZWciLCJpYXQiOjE1ODg0MTE2NzF9.VkS0wlk9yf1FVkx6i_CzrhlgykLpILZBG0XuX2rxiYQ"
}

### sign out
DELETE http://localhost:3001/signout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJUWE1qdHhGbUdPS04wLUdtbDloZWciLCJpYXQiOjE1ODg0MTE2NzF9.VkS0wlk9yf1FVkx6i_CzrhlgykLpILZBG0XuX2rxiYQ"
}


# USERS
###
GET http://localhost:3001/users

###
GET http://localhost:3001/users/G2sfevB3JaUV9ShGD7evX

###
POST http://localhost:3001/users
Content-Type: application/json

{
  "login": "johndoe",
  "password": "321"
}

###
PUT http://localhost:3001/users/1FDNwrI2zTaoKP7eAGx1B7
Content-Type: application/json

{
  "login": "janedoe",
  "password": "111"
}

###
// resource update by ID
PATCH http://localhost:3001/users/yI27PJUxb_6aDf9-y0YfQ
Content-Type: application/json

{
  "password": "456"
}

###
// resource deletion by ID
DELETE http://localhost:3001/users/QsuK-fjM-Msd7lWTQD8Qq
